---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake spec"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
notifications:
  email: false
